[package]
name = "classfile"
version = "0.0.1"
edition = "2021"
publish = false
authors = [
    "Andrew Duffy <andrew@a10y.dev>"
]
license = "MIT"
description = "A simple, teachable parser for the Java Virtual Machine ClassFile format"

[dependencies]
bytes = "1"
thiserror = "1.0.58"
